# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/model/named_entity_recognition_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/model/named_entity_recognition_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n1services/model/named_entity_recognition_rpc.proto\"\x1d\n\x0cInputMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rOutputMessage\x12\r\n\x05value\x18\x01 \x01(\t26\n\x0bShowMessage\x12\'\n\x04show\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32\x38\n\x0eTaggingMessage\x12&\n\x03tag\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32>\n\x0fTokenizeMessage\x12+\n\x08tokenize\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x32\x38\n\x0c\x43hunkMessage\x12(\n\x05\x63hunk\x12\r.InputMessage\x1a\x0e.OutputMessage\"\x00\x62\x06proto3')
)




_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='InputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)


_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='OutputMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE
DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'services.model.named_entity_recognition_rpc_pb2'
  # @@protoc_insertion_point(class_scope:InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'services.model.named_entity_recognition_rpc_pb2'
  # @@protoc_insertion_point(class_scope:OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)



_SHOWMESSAGE = _descriptor.ServiceDescriptor(
  name='ShowMessage',
  full_name='ShowMessage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=116,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='show',
    full_name='ShowMessage.show',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWMESSAGE)

DESCRIPTOR.services_by_name['ShowMessage'] = _SHOWMESSAGE


_TAGGINGMESSAGE = _descriptor.ServiceDescriptor(
  name='TaggingMessage',
  full_name='TaggingMessage',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=172,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='tag',
    full_name='TaggingMessage.tag',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAGGINGMESSAGE)

DESCRIPTOR.services_by_name['TaggingMessage'] = _TAGGINGMESSAGE


_TOKENIZEMESSAGE = _descriptor.ServiceDescriptor(
  name='TokenizeMessage',
  full_name='TokenizeMessage',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=230,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='tokenize',
    full_name='TokenizeMessage.tokenize',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOKENIZEMESSAGE)

DESCRIPTOR.services_by_name['TokenizeMessage'] = _TOKENIZEMESSAGE


_CHUNKMESSAGE = _descriptor.ServiceDescriptor(
  name='ChunkMessage',
  full_name='ChunkMessage',
  file=DESCRIPTOR,
  index=3,
  options=None,
  serialized_start=294,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='chunk',
    full_name='ChunkMessage.chunk',
    index=0,
    containing_service=None,
    input_type=_INPUTMESSAGE,
    output_type=_OUTPUTMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHUNKMESSAGE)

DESCRIPTOR.services_by_name['ChunkMessage'] = _CHUNKMESSAGE

# @@protoc_insertion_point(module_scope)
